version: 0.2

phases: 
    install: 
      runtime-versions:
        nodejs: 10
      commands:
        - npm install -g serverless@1.57.0
    pre_build:
      commands:
        - npm install
    build:
      commands:
        - mocha test/parser.test.js --reporter mochawesome
reports: 
  group1:
    files:
      - 'mochawesome-report/mochawesome.json'
artifacts:
  files:
  - ./**/*