version: 0.2

phases: 
    install: 
      runtime-versions:
        nodejs: 10
      commands:
        - npm install -g serverless@1.57.0
    pre_build:
      commands:
        - npm install
    build:
      commands:
        - npm run test
reports: 
  group1:
    files:
      - 'zzzcg-code-build-test-report.json'
    commands:
        - npm run test
artifacts:
  files:
  - ./**/*